CREATE TABLE IF NOT EXISTS winners (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  winner TEXT NOT NULL,
  members TEXT NOT NULL DEFAULT '',
  score REAL NOT NULL DEFAULT 0,
  rounds INTEGER NOT NULL DEFAULT 0,
  teams INTEGER NOT NULL DEFAULT 0,
  standings TEXT NOT NULL DEFAULT '[]',
  date TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_winners_date ON winners(date DESC);
